stages:
  - build
  - test

maven-build:
  stage: build
  image: maven:3.8-jdk-11-slim
  before_script:
    - cd app
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - app/target/*.jar
  when: manual
  only:
    - main
  tags:
    - dev

maven-test:
  stage: test
  image: maven:3.8-jdk-11-slim
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#hello test
  artifacts:
    paths:
      - app/target/*.jar
  when: manual
  only:
    - main
  tags:
    - dev

