stages:
  - test

test-case-1:
  stage: test
  image: openjdk:8-jdk-alpine
  before_script:
    - cd app
  script:
    - echo "Starting to test"
    - mvn -Dtest=AppTest#hello test
  when: manual
  only:
    - main
  tags:
    - dev