variables:
  IMAGE_NAME: gitlab-ecs-app:latest
  ECR: 632296647497.dkr.ecr.eu-central-1.amazonaws.com

image: docker:latest
services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR

stages:
  - build
  - test
  - image
  - deploy

maven-build:
  stage: build
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - app/target/*.jar
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-1:
  stage: test
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test1 test
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-2:
  stage: test
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test2 test
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-3:
  stage: test
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test3 test
  when: manual
  only:
    - main
  tags:
    - dev

image-build:
  stage: image
  script:
    - docker build -t "${ECR}/${IMAGE_NAME}" .
  when: manual
  only:
    - main
  tags:
    - dev

image-push:
  stage: image
  script:
    - docker push "${ECR}/${IMAGE_NAME}"
  dependencies:
    - image-build  
  when: manual
  only:
    - main
  tags:
    - dev

deploy-aws-cli:
  stage: deploy
  script:
    - aws ecs create-cluster --cluster-name demo-cluster --region $AWS_DEFAULT_REGION
    - aws ecs register-task-definition --cli-input-json file://ecs/fargate-task.json
    - aws ecs create-service --cli-input-json file://ecs/fargate-service.json --region $AWS_DEFAULT_REGION
  when: manual
  only:
    - main
  tags:
    - dev