variables:
  IMAGE_NAME: kurtay/gitlab-ecs-app

image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - docker

maven-build:
  stage: build
  image: maven:3.8-jdk-11-slim
  before_script:
    - cd app
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - app/target/*.jar
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-1:
  stage: test
  image: maven:3.8-jdk-11-slim
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test1 test
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-2:
  stage: test
  image: maven:3.8-jdk-11-slim
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test2 test
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-3:
  stage: test
  image: maven:3.8-jdk-11-slim
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test3 test
  when: manual
  only:
    - main
  tags:
    - dev

docker-build:
  stage: docker
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME .
  when: manual
  only:
    - main
  tags:
    - dev

docker-push:
  stage: docker
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker push $IMAGE_NAME
  when: manual
  only:
    - main
  tags:
    - dev