stages:
  - test

test-case-1:
  stage: test
  image: maven:3.8-jdk-11-slim
  before_script:
    - cd app
  script:
    - echo "Starting to test"
    - mvn -Dtest=AppTest#hello test
  when: manual
  only:
    - main
  tags:
    - dev