variables:
  IMAGE_NAME: kurtay/gitlab-ecs-app

image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - image
  - deploy

maven-build:
  stage: build
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - app/target/*.jar
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-1:
  stage: test
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test1 test
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-2:
  stage: test
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test2 test
  when: manual
  only:
    - main
  tags:
    - dev

maven-test-3:
  stage: test
  image: maven:3.6-jdk-8-alpine
  before_script:
    - cd app
  script:
    - mvn -Dtest=AppTest#test3 test
  when: manual
  only:
    - main
  tags:
    - dev

image-build:
  stage: image
  script:
    - docker build -t $IMAGE_NAME .
  when: manual
  only:
    - main
  tags:
    - dev

image-push:
  stage: image
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker push $IMAGE_NAME
  dependencies:
    - docker-build  
  when: manual
  only:
    - main
  tags:
    - dev

deploy-ecs:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  variables:
    AWS_PROFILE: test
  script:
    - aws --version
    - aws sts get-caller-identity
  when: manual
  only:
    - main
  tags:
    - dev